version: "3.8"
services:
  backend-flask:
    environment:
      FRONTEND_URL: "https://${CODESPACE_NAME}-3000.app.github.dev" #github codespace specific url
      BACKEND_URL: "https://${CODESPACE_NAME}-4567.app.github.dev"
#      BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://${CODESPACE_NAME}-4567.app.github.dev"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js